### ISSUE TITLE
Sound Menu deposite

### ISSUE THREAD

**Issue by LeRoiDamien** [OmerBenGera/SuperiorSkyblock2#36]
Hello, since the last version of the plugin I have this error
Version : b39

http://pastebin.fr/81605

**Comment by LeRoiDamien** [comment]
I have another problem also I don't know if I put it here too

**Comment by OmerBenGera** [comment]
Fixed in build #40

**Comment by LeRoiDamien** [comment]
thank you so much

**Comment by LeRoiDamien** [comment]
hello, sorry I still have the error
http://pastebin.fr/81655

**Comment by OmerBenGera** [comment]
Check out build #42

**Comment by LeRoiDamien** [comment]
thank you
